title: <p align="center"> Jahana Shirin </p>
logo: /assets/img/logo.png
description:
  <p align="center">
  <a href="https://github.com/Jahana-s">GitHub</a>
  
  <br>   
  Data Analyst by the day, homemaker by night.
  <br>
  </p>

theme: jekyll-theme-minimal
